### ISSUE TITLE
App doesn't open on Linux Mint

### ISSUE THREAD

**Issue by Da-vid21** [powenn/AltServer-LinuxGUI#18]
I installed the app using the apt way and the dpkg, and it shows up on my start menu, but when I try to launch it, it doesn't work

**Comment by hthre7** [comment]
> I installed the app using the apt way and the dpkg, and it shows up on my start menu, but when I try to launch it, it doesn't work


similar result with the following error:
```sh
Traceback (most recent call last):
  File "UI.py", line 6, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller/loader/pyimod03_importers.py", line 495, in exec_module
  File "Main.py", line 24, in <module>
OSError: [Errno 6] No such device or address
[17733] Failed to execute script 'UI' due to unhandled exception!
```

**Comment by Staubgeborener** [comment]
> > I installed the app using the apt way and the dpkg, and it shows up on my start menu, but when I try to launch it, it doesn't work
> 
> similar result with the following error:
> 
> ```shell
> Traceback (most recent call last):
>   File "UI.py", line 6, in <module>
>   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
>   File "PyInstaller/loader/pyimod03_importers.py", line 495, in exec_module
>   File "Main.py", line 24, in <module>
> OSError: [Errno 6] No such device or address
> [17733] Failed to execute script 'UI' due to unhandled exception!
> ```

Same problem with manjaro @powenn

**Comment by aashish-choudhary** [comment]
@Da-vid21 @hthre7 @Staubgeborener make sure you aren't using wayland, try to run it with xorg ie

- Log out
- Select your user, then before login 
- Click on gear icon at the right bottom -> select xorg
- then login and try launching it

**Comment by TheCheddarCheese** [comment]
i have almost the same thing except i can run it through the terminal

**Comment by powenn** [comment]
use python script instead , this project is outdated
